apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-playground
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/MarWeUMR/argocd-playground
        revision: helmfile
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/MarWeUMR/argocd-playground
        path: "{{ .path.path }}"
        targetRevision: helmfile
        plugin:
          name: argocd-lovely-plugin
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
