---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgBAAC+4vRmz53Ekn23CYsybLukDacpw+9fOWa/BApZ3HcEsX0Pjfxx/rzDBjIL2+xoAbjbDbp1Fh9yW58dgv0NrkFJ3H5G7rgPjn/yRvgqTymjCPu0nEyuNVITUYqJH8rAjjuTcoMrEMpgqtYYpQWr6qeJRgOj5r9eoO1Tt+RtVdXAiLtw0EYa46L/g0JFV8xwc4VRO4in0o0RHyNSfRGOXv7ZWu2rSEUbV9Wyikqf6+YZuTRFaYGYtEIxCgxvqhJXaj2w9jyQLSaQZ0hPeq3NkvHGVGYdOOwFnEAbQA0V4WOL+YNps95EUDon7wZIojrFhtXZoviYzt/17zj49hZ22jr9rZsmUj21qMB4pSqfN97+Yx7OLVG5Kq5/CGiTjcLr2yJK4hkgfnQxCS9a835t4cUH4Ir25w/LGs+lwAN6tSDP4zOSve1ycmkA4RZd6yhEUlo4SEMmqeBeO+xFVudF15+V4WCeVu1oF3wFH7muWapIskSDkxRwu1iES+s3Nog+kKqNp2zA90woHsaIgUtCCswcjgxnlG2j2UEYvbRc7EannhFFrQa7macJoq8j94YFACEUMf9/QgKLGfelSp5BhhYOR1b9iVF+Ivq76IjExor2UUnIenNi5ay5XnLEap7loaWFy4LjBHswPGwvGO5gLWG/3dx39/COawN57ZFXJvoyYgkA8vypyCnpeSLhDnZkhftU6eeV8kcqPkyayUtDi+2KX2uEwh4OXqAl/kxAz6w==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: default
