apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-operator
  namespace: "{{ .Values.dataDog.applicationNamespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "{{ .Values.dataDog.namespace }}"
    server: "{{ .Values.dataDog.destinationServer }}"
  project: default
  source:
    repoURL: "{{ .Values.dataDog.repoURL }}"
    path: "{{ .Values.dataDog.path }}"
    targetRevision: "{{ .Values.dataDog.targetRevision }}"
    chart: "{{ .Values.dataDog.chart }}"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
