apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-operator
  namespace: "{{ .Values.dataDog.applicationNamespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "{{ .Values.dataDog.namespace }}"
    server: "{{ .Values.dataDog.destinationServer }}"
  project: default
  sources:
    - chart: "{{ .Values.dataDog.chart }}"
      repoURL: "{{ .Values.dataDog.chartURL }}"
      path: "{{ .Values.dataDog.path }}"
      targetRevision: "{{ .Values.dataDog.chartRevision }}"
      helm:
        values: |
          datadog:
            apiKeyExistingSecret: datadog-secret
            site: datadoghq.eu
            clusterName: default
            processAgent:
              enabled: true
              processCollection: false

            logs:
              enabled: false
              containerCollectAll: false

            networkMonitoring:
              enabled: false

          agents:
            image:
              tag: latest
              tagSuffix: jmx
            process_config:
              enabled: true
    - path: datadog
      repoURL: "{{ .Values.dataDog.repoURL }}"
      targetRevision: "{{ .Values.dataDog.targetRevision }}"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
