prometheus:
  service:
    type: NodePort
  prometheusSpec:
    enableRemoteWriteReceiver: true
    podMonitorSelector:
      matchLabels:
        monitorMe: "yesPlease"
grafana:
  adminPassword: BadPassword@1
  service:
    type: NodePort
