prometheus:
  service:
    type: NodePort
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "ssh_tunnel_prometheus"
        static_configs:
          - targets: ["localhost:9091"]
    enableRemoteWriteReceiver: true
    podMonitorSelector:
      matchLabels:
        monitorMe: "yesPlease"
grafana:
  adminPassword: BadPassword@1
  service:
    type: NodePort
