prometheus:
  service:
    type: NodePort
  prometheusSpec:
    remoteWriteDashboards: true
    # additionalScrapeConfigs:
    #   - job_name: "ssh_tunnel_prometheus"
    #     static_configs:
    #       - targets: ["127.0.0.1:9091"]
    enableRemoteWriteReceiver: true
    podMonitorSelector:
      matchLabels:
        monitorMe: "yesPlease"
grafana:
  adminPassword: BadPassword@1
  service:
    type: NodePort
