prometheus:
  service:
    type: NodePort
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        monitorMe: "yesPlease"

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer

grafana:
  adminPassword: BadPassword@1
  service:
    type: NodePort
