apiVersion: ENC[AES256_GCM,data:qd8=,iv:I6jhfG3EAdxFuoXEuk3CjCufXqwjVLTBSmbztgoMqfM=,tag:uYmVZT1tCvdIeogRQomNSQ==,type:str]
data:
    api-key: ENC[AES256_GCM,data:ChYNmjh3E31UAbUyXN8SO7wzQVchZZbLmYLR6NmcctxIad2Me36W3hJ8rl4=,iv:ZsvXnJKuI//m6acMBgZWviZG0UvgZkW+PwTnxxJFWtA=,tag:8vWE0au1c/XUp694awZ3ow==,type:str]
kind: ENC[AES256_GCM,data:BnXcDkw0,iv:/GMSfnJPfSfL6+PSUe9cIFX0v5MWmPV2AL3zcJzhzlg=,tag:g9FGO83OIwWjB+9ja4MXXA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:hz1GkLiH+knC21C6CnWR,iv:e4PqktMhE/K9xVRiceo8BCFOUA6STMyp20aih892N+w=,tag:OeOqoTcmZwp1YtmVe/10Nw==,type:str]
    namespace: ENC[AES256_GCM,data:kTIEhcARFpkPVw==,iv:0pRjKV3SUZxnX62Z5WLzP5vnPCzy1LQTH+sU96BmRug=,tag:R4ABskTx2+pxegegGPGSbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzx53fya208fy8agh9nv5wxkrlulh6e7n7czv07eth3sswydneas07u5zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ3dwalRPYk4zNU5TcHZl
            TnhIeTk0eDZOUVVxUWtUazBsUmNON3kvTGxnCmpJYWtWVzlmcysxck1GTkNRVkJk
            V0I1bkk5VlI5S3NEb0lUaUJqNmQ3bnMKLS0tIDZOVWgzVWl1MXRDcGgwZ055YVcv
            QkYxTmRHNURLdStmdFJ4QTE3SDkrcHMKEyjKwZ6LakpXUIPEDbrb05U7pRwsQ6HY
            DTUN0fHkLVbUcfKNv1NF3S1Lb1DYNJrOxj4seIXf6jg4WrXqO2y5vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T08:44:30Z"
    mac: ENC[AES256_GCM,data:+CEPrgqen5NMDF1I+vGtWAnoXacKjeFyI8g7AayahIsR7rWXg020U/w+ynCnIjgkRYjiQWGUf4ZEypE2XXiaNFPoajIedOFvBRrV+iTRicI3Sv4xPRPea7WlnBi1CcfcYa1uqNPDrffbj/dzXbWEl6T4+/89MaPX9UI1q1Msj7Q=,iv:i1Ca3JegpopqBvVBNWwGZqV7tb7ayh72a9yJJOPJCL4=,tag:MUpZ9tajD4U5j6usXKCIHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
