---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgAxtWsdZ737nrQxtZxD9FYvs3kZd477XIHVHxscbTKKEJ4MA2v6ZBcFBiuMdZOefPOQGqX1U5CCRWvKqJny5D4IHCtD76bcRnpGh//YUibAvhH+PmTxtj5w+Nfaf0HTB/8S5XxYUdOjEdGpPJJMSS2OiEGfRiSc1Lbj3AIMjHHxkT1rCHFpGiLiZdHDiy4a/l/j3h1hV/NYe8HV4MURbXZdOkku6ITYTAH18DYJ4JmU7BJSKDvczJE+efNeaOi8eeNvzfRFJl1xKA6kuZk7kD0EZvAMtshPsjNHn8Tb8lN9g0Q8uUASVWnZoSe3EyKf9bC/uNJvbqSf665fl164V+M41dIIQH0wAnh7wyS2pZZuKdUFdg9WIqWbqcw7v9IcvweRRZjEba50Bw5nqMYokJi3dAl7kU0JSE4C626efFzBjvulChn160JzM6QZUC/JoDeNinPcObY3+HDO71pffzaH+t3j/aOjxyIgsPUt9HTyJ8vji/9SD/rShhw84K8AaOzjofZ++69sqrdTA/fIwoYoLz9KAClC9/WSM0X1zcY4rKgRZNNL7T5/8d95urf2Nwa8DedbD/l+uYD1TcsMumY/I+YlfBDS8PpUui7RN8iY5oE/3OLCuNpHMLhzyPPZdoT5NqrZEisiQ17fjseK+IZaD6JLp9mvelMQH94ZJyFavFAM4lTrli5xXBqv9amxORvbhsI34r2RCzxOOmLmvLifWkuceXjGoqmxxf1Jp8N9xg==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: monitoring
